### ISSUE TITLE
null pointer exception when key exists but not attributes

### ISSUE THREAD

**Issue by leoromanovsky** [ucirello/dynamolock#2]
When a lock is loaded using a certain key, but none of the other attributes exist in the table, the following code throws a null pointer exception: https://github.com/ucirello/dynamolock/blob/master/client.go#L593-L611

When parsing the date. I believe it should be modified to be more defensive and raise an error whenever one of the expected attribute values is missing.

I'm happy to submit a review if you are busy. As a side note, I've been having trouble building this project .. something to do with the vanity URL. What command do you execute to `go compile` ?

**Comment by ucirello** [comment]
@leoromanovsky Thanks for reporting this bug! And sorry for the closed PR.

**Comment by ucirello** [comment]
> I'm happy to submit a review if you are busy. As a side note, I've been having trouble building this project .. something to do with the vanity URL. What command do you execute to go compile ?

You should use cirello.io/dynamolock instead.

**Comment by ucirello** [comment]
@leoromanovsky can you provide a test case that proves the bug?

**Comment by ucirello** [comment]
@leoromanovsky could you please confirm whether dd91cad fixes the case?

**Comment by ucirello** [comment]
@leoromanovsky I am going to close this - but please reopen if necessary.
